### PR TITLE
Change server default port from 3000 to 8080

### PR DESCRIPTION
**Pull request by brunobottazzini**
To be more friendly user it is good to put it in a common port

Depending on the linux distro it may ask to be root when running
the server

Signed-off-by: Bruno Bottazzini bruno.bottazzini@intel.com

### CODE REVIEW

**Comment by anselmolsm** [comment]
I believe we should change the default port to 80 while installing in specific cases (e.g. boards).
Users running soletta-dev-app as ordinary users will face permission issues with port 80.

**Comment by ibriano** [comment]
On Tue, 06 Oct 2015 10:38:49 -0700, Anselmo L. S. Melo wrote:

> I believe we should change the default port to 80 while installing in specific cases (e.g. boards).
> Users running soletta-dev-app as ordinary users will face permission issues with port 80.

Agreed. Also, if you want something more standard that won't require
root permissions, default to 8080.

**Comment by anselmolsm** [comment]
+1 for 8080.

**Comment by brunobottazzini** [comment]
@ibriano, you are right! The port 8080 is really common and way more right than 3000. 

But in the end it will have the same behavior as the port 3000, the user will have to put "http://IP_ADDRES:8080" which in case http://IP_ADDRESS would be better.

@anselmolsm why not create an algorithm that will pass some interface like "It is needed to be root when running on port 80, change it on the configuration or run as root". Something like this...

**Comment by barbieri** [comment]
the default configuration file should be 8080, the installer (ie: rpm, deb, etc...) should change to 80.

eventually we can offer an install option to choose the port to be used.

**Comment by brunobottazzini** [comment]
alright I will update the patch to be 8080 

and for the installers we change to be 80 :+1:

**Pull request merged**
